"""empty message

Revision ID: d887d6db9550
Revises: 63fcbc0f9487
Create Date: 2023-06-17 01:12:03.977491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd887d6db9550'
down_revision = '63fcbc0f9487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_comments', sa.String(length=80), nullable=False))
        batch_op.drop_column('aditional_coments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_coments', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('aditional_comments')

    # ### end Alembic commands ###
