"""empty message

Revision ID: e2936aff7c5a
Revises: 6dc2a6f061dc
Create Date: 2023-06-29 20:30:09.844507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2936aff7c5a'
down_revision = '6dc2a6f061dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
